[test]
description = "Run tests."
run = "#!/usr/bin/env sh\n\nset -- \"$PWD\" \"$@\"\ncd \"$MISE_PROJECT_ROOT\"/\"./mise-sh/\"\n. \"project.lib.sh\"\ncd \"$1\"\nshift\n\"task_test\" \"$@\""

[run]
description = "Run cmd."
run = "#!/usr/bin/env sh\n\nset -- \"$PWD\" \"$@\"\ncd \"$MISE_PROJECT_ROOT\"/\"./mise-sh/\"\n. \"project.lib.sh\"\ncd \"$1\"\nshift\n\"task_run\" \"$@\""

[doc]
description = "Update documentation files."
run = "#!/usr/bin/env sh\n\nset -- \"$PWD\" \"$@\"\ncd \"$MISE_PROJECT_ROOT\"/\"./mise-sh/\"\n. \"project.lib.sh\"\ncd \"$1\"\nshift\n\"task_doc\" \"$@\""
